spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        type:
          preferred_enum_jdbc_type: VARCHAR
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never

  main:
    allow-bean-definition-overriding: true

  task:
    execution:
      pool:
        core-size: 1
        max-size: 2
        queue-capacity: 100
    scheduling:
      pool:
        size: 1

football-data:
  api:
    base-url: https://api.football-data.org/v4
    token: test-token
    competition-ids:
      - 2014
      - 2021
      - 2015
      - 2002
      - 2019
