spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/player_market
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create / update / validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

# Football-Data.org API Configuration
football-data:
  api:
    base-url: ${FOOTBALL_DATA_BASE_URL:https://api.football-data.org/v4}
    token: ${FOOTBALL_DATA_TOKEN}
    competition-ids:
      - 2014  # LaLiga
      - 2021  # Premier League
      - 2015  # Ligue 1
      - 2002  # Bundesliga
      - 2019  # Serie A
