ALTER TABLE player ADD COLUMN IF NOT EXISTS total_tokens integer NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN IF NOT EXISTS available_tokens integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS balance numeric(19,8) NOT NULL DEFAULT 0;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN', 'SUPERUSER'));
